### ISSUE TITLE
MacRoman conversion doesn't seem to be working correctly

### ISSUE THREAD

**Issue by andrews05** [tjhancocks/kestrel-development-kit#35]
**Describe the bug/issue**
The accented characters in resource types are not being converted correctly from utf-8 to macroman.

**To Reproduce**
Assemble the following test file.
```
declare SpriteAnimation {
	new (id = #700, name = "Stars") {
		sprites = #700;
		size = 10 10;
		tiles = 1 1;
	}
}
```

**Expected behavior**
The ï character in spïn should be written as 0x95 in the output file but it ends up as unicode 0xEF.

[edit] Figured it out, it should push_back(j) not push_back(cp_table[j]). Will submit PR...

**Comment by tjhancocks** [comment]
Yeah I seem to recall spotting something like that a while ago but not paying it any mind due to being in the middle of something else... must have just completely washed over me.

Approved that, so feel free to merge whenever.

**Comment by andrews05** [comment]
I don't have write access, will have to leave the merging to you :)
